import DYNAMIC_LINE_BAR_MIX from './DYNAMIC_LINE_BAR_MIX'
import DYNAMIC_RANKING_BAR from './DYNAMIC_RANKING_BAR'
import LINE_BASICS from './LINE_BASICS'
import PIE_BASICS from './PIE_BASICS'
import BAR_BASICS from './BAR_BASICS'
import RING_BASICS from './RING_BASICS'

export default {
    DYNAMIC_LINE_BAR_MIX: DYNAMIC_LINE_BAR_MIX,
    DYNAMIC_RANKING_BAR: DYNAMIC_RANKING_BAR,
    LINE_BASICS: LINE_BASICS,
    PIE_BASICS,
    BAR_BASICS,
    RING_BASICS
}