name: deploy github pages
on:
    push:
        branches:
            - main
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: 1. Checkout
              uses: actions/checkout@master

            - name: 2. setup nodejs...

              uses: actions/setup-node@v2
              with:
                node-version: '16'

            - name: 3. pnpm install
              run: |
                  
                  pnpm i

            - name: 4. build pages..
              run: |
                  pnpm build
                  ls

            - name: 5. deploy github pages
              uses: JamesIves/github-pages-deploy-action@3.7.1
              with:
                  ACCESS_TOKEN: ${{ secrets.PAGES_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: dist
